version: '3.8'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA : "Y"
      SA_PASSWORD: "abcd1234!"
      MSSQL_PID: "Express"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mssql-entrypoint.sh:/mssql-entrypoint.sh
    command: /bin/bash /mssql-entrypoint.sh