version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
      - MSSQL_ENABLE_HADR=0
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    command:
      - /opt/mssql/bin/sqlservr
      - -T1118

volumes:
  mssql_data: